title: JTFR Unit Information
description: test
theme: just-the-docs

url: https://jtf-r.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Aux links for the upper right navigation
aux_links:
  "Join the JTF:R Discord!":
    - "https://discord.gg/brRcbYyGng"

# Set a path/url to a logo that will be displayed instead of the title
# logo: "/assets/images/jtfr.png"
