title: Joint Task Force: Romeo - Unit Information
description: 
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Color scheme supports "light" (default) and "dark"
color_scheme: dark

# Aux links for the upper right navigation
aux_links:
  "Join the JTF:R Discord!":
    - "https://discord.gg/brRcbYyGng"
